spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/myGym
    username: sa
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 50

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis

  data:
    redis:
      host: 127.0.0.1
      port: 6379

server:
  error:
    include-message: always

logging:
  level:
    org:
      hibernate:
        SQL: debug

jwt:
  secret-key: 1fbb154ceb5ad8f0cf24837f4c0a4f01777a0066baef8c21919f52c72f5db199